### PR TITLE
Add build_deb.sh script to build a .deb package 

### PR DESCRIPTION
**Pull request by danobi**
This script is helpful for ubuntu packaging.

In the future this could be hooked up to CI to automatically generate
.deb artifacts on release.

### CODE REVIEW

**Comment by dschatzberg** [comment]
Hey @danobi. Hope you're doing well. This look great, thanks for adding it

**Comment by danobi** [comment]
Hi @dschatzberg , looks like https://github.com/facebookincubator/below/commit/1c4a01fe3475d3ed725fb0021a596daa3c46dedc blew away some of the Cargo.toml changes. I think you might need to manually add the changes to the internal mapping stuff.

**Comment by dschatzberg** [comment]
@danobi Should be fixed with https://github.com/facebookincubator/below/commit/69f0e3f8c09454b9f77d12d41268ee3cb53a523f - please let me know if it still doesn't work

**Comment by danobi** [comment]
@dschatzberg thank you!

**Pull request closed without merging**
